/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddStudentRequest {
  'prn' : string,
  'name' : string,
  'section' : string,
  'isActive' : boolean,
  'rollNo' : bigint,
}
export interface AttendanceRecord {
  'id' : string,
  'prn' : string,
  'student_name' : string,
  'latitude' : number,
  'method' : string,
  'face_mismatch' : boolean,
  'image_url' : string,
  'device_info' : string,
  'longitude' : number,
  'timestamp' : bigint,
  'geo_fail' : boolean,
}
export interface AttendanceStats {
  'unique_students' : bigint,
  'total_students' : bigint,
  'today_count' : bigint,
  'total_records' : bigint,
}
export interface FacultyCredentials {
  'password' : string,
  'name' : string,
  'email' : string,
}
export interface LocationConfig {
  'lat' : number,
  'lng' : number,
  'locationLabel' : string,
  'radiusMeters' : number,
}
export interface ManualAttendanceRequest {
  'prn' : string,
  'subject' : string,
  'timestamp_override' : [] | [bigint],
  'notes' : string,
}
export interface MarkAttendanceRequest {
  'prn' : string,
  'latitude' : number,
  'token' : bigint,
  'image_url' : string,
  'device_info' : string,
  'longitude' : number,
}
export type MarkAttendanceResponse = { 'ok' : string } |
  { 'alreadyMarked' : string } |
  { 'error' : string } |
  { 'invalidPRN' : string };
export interface SectionCounts {
  'first_year' : bigint,
  'btech' : bigint,
  'third_year' : bigint,
  'second_year' : bigint,
}
export interface Student {
  'id' : string,
  'prn' : string,
  'reference_photo_url' : [] | [string],
  'name' : string,
  'section' : string,
  'isActive' : boolean,
  'rollNo' : bigint,
}
export interface StudentWithId {
  'prn_last2' : string,
  'name' : string,
  'student_id' : string,
}
export interface StudentWithSection {
  'id' : string,
  'prn' : string,
  'reference_photo_url' : [] | [string],
  'name' : string,
  'section' : string,
  'isActive' : boolean,
  'rollNo' : bigint,
}
export interface UpdateStudentRequest {
  'prn' : [] | [string],
  'name' : [] | [string],
  'section' : [] | [string],
  'isActive' : [] | [boolean],
  'rollNo' : [] | [bigint],
}
export interface WeeklySlot {
  'day' : string,
  'startTime' : string,
  'subject' : string,
  'endTime' : string,
  'room' : string,
}
export interface _SERVICE {
  'add_manual_attendance' : ActorMethod<
    [ManualAttendanceRequest],
    MarkAttendanceResponse
  >,
  'add_student' : ActorMethod<
    [AddStudentRequest],
    { 'ok' : Student } |
      { 'err' : string }
  >,
  'delete_attendance' : ActorMethod<[bigint], boolean>,
  'delete_student' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'flag_face_mismatch' : ActorMethod<[bigint, boolean], boolean>,
  'get_all_attendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'get_all_semester_templates' : ActorMethod<
    [],
    Array<[bigint, Array<WeeklySlot>]>
  >,
  'get_all_students' : ActorMethod<[], Array<Student>>,
  'get_attendance_by_date' : ActorMethod<[string], Array<AttendanceRecord>>,
  'get_attendance_by_student' : ActorMethod<[string], Array<AttendanceRecord>>,
  'get_attendance_stats' : ActorMethod<[], AttendanceStats>,
  'get_faculty_credentials' : ActorMethod<[], FacultyCredentials>,
  'get_hotspot_ip' : ActorMethod<[], string>,
  'get_live_checkins' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'get_location_config' : ActorMethod<[], LocationConfig>,
  'get_semester_template' : ActorMethod<[bigint], Array<WeeklySlot>>,
  'get_student_by_prn' : ActorMethod<[string], [] | [Student]>,
  'get_student_list' : ActorMethod<[], Array<StudentWithId>>,
  'get_student_sections_count' : ActorMethod<[], SectionCounts>,
  'get_students_by_section' : ActorMethod<[string], Array<StudentWithSection>>,
  'mark_attendance' : ActorMethod<
    [MarkAttendanceRequest],
    MarkAttendanceResponse
  >,
  'update_faculty_credentials' : ActorMethod<[string, string, string], boolean>,
  'update_hotspot_ip' : ActorMethod<[string], boolean>,
  'update_location_config' : ActorMethod<
    [LocationConfig],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'update_semester_template' : ActorMethod<
    [bigint, Array<WeeklySlot>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'update_student' : ActorMethod<
    [string, UpdateStudentRequest],
    { 'ok' : Student } |
      { 'err' : string }
  >,
  'update_student_photo' : ActorMethod<[string, string], [] | [Student]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];