/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ManualAttendanceRequest = IDL.Record({
  'prn' : IDL.Text,
  'subject' : IDL.Text,
  'timestamp_override' : IDL.Opt(IDL.Int),
  'notes' : IDL.Text,
});
export const MarkAttendanceResponse = IDL.Variant({
  'ok' : IDL.Text,
  'alreadyMarked' : IDL.Text,
  'error' : IDL.Text,
  'invalidPRN' : IDL.Text,
});
export const AddStudentRequest = IDL.Record({
  'prn' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'isActive' : IDL.Bool,
  'rollNo' : IDL.Nat,
});
export const Student = IDL.Record({
  'id' : IDL.Text,
  'prn' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'isActive' : IDL.Bool,
  'rollNo' : IDL.Nat,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Text,
  'prn' : IDL.Text,
  'student_name' : IDL.Text,
  'latitude' : IDL.Float64,
  'method' : IDL.Text,
  'image_url' : IDL.Text,
  'device_info' : IDL.Text,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
  'geo_fail' : IDL.Bool,
});
export const WeeklySlot = IDL.Record({
  'day' : IDL.Text,
  'startTime' : IDL.Text,
  'subject' : IDL.Text,
  'endTime' : IDL.Text,
  'room' : IDL.Text,
});
export const AttendanceStats = IDL.Record({
  'unique_students' : IDL.Nat,
  'total_students' : IDL.Nat,
  'today_count' : IDL.Nat,
  'total_records' : IDL.Nat,
});
export const FacultyCredentials = IDL.Record({
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const LocationConfig = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'locationLabel' : IDL.Text,
  'radiusMeters' : IDL.Float64,
});
export const StudentWithId = IDL.Record({
  'prn_last2' : IDL.Text,
  'name' : IDL.Text,
  'student_id' : IDL.Text,
});
export const SectionCounts = IDL.Record({
  'first_year' : IDL.Nat,
  'btech' : IDL.Nat,
  'third_year' : IDL.Nat,
  'second_year' : IDL.Nat,
});
export const StudentWithSection = IDL.Record({
  'id' : IDL.Text,
  'prn' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'isActive' : IDL.Bool,
  'rollNo' : IDL.Nat,
});
export const MarkAttendanceRequest = IDL.Record({
  'prn' : IDL.Text,
  'latitude' : IDL.Float64,
  'token' : IDL.Nat,
  'image_url' : IDL.Text,
  'device_info' : IDL.Text,
  'longitude' : IDL.Float64,
});
export const UpdateStudentRequest = IDL.Record({
  'prn' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'section' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
  'rollNo' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'add_manual_attendance' : IDL.Func(
      [ManualAttendanceRequest],
      [MarkAttendanceResponse],
      [],
    ),
  'add_student' : IDL.Func(
      [AddStudentRequest],
      [IDL.Variant({ 'ok' : Student, 'err' : IDL.Text })],
      [],
    ),
  'delete_attendance' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'delete_student' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'get_all_attendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'get_all_semester_templates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(WeeklySlot)))],
      ['query'],
    ),
  'get_all_students' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'get_attendance_by_date' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'get_attendance_by_student' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'get_attendance_stats' : IDL.Func([], [AttendanceStats], ['query']),
  'get_faculty_credentials' : IDL.Func([], [FacultyCredentials], ['query']),
  'get_hotspot_ip' : IDL.Func([], [IDL.Text], ['query']),
  'get_live_checkins' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'get_location_config' : IDL.Func([], [LocationConfig], ['query']),
  'get_semester_template' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(WeeklySlot)],
      ['query'],
    ),
  'get_student_by_prn' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'get_student_list' : IDL.Func([], [IDL.Vec(StudentWithId)], ['query']),
  'get_student_sections_count' : IDL.Func([], [SectionCounts], ['query']),
  'get_students_by_section' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentWithSection)],
      ['query'],
    ),
  'mark_attendance' : IDL.Func(
      [MarkAttendanceRequest],
      [MarkAttendanceResponse],
      [],
    ),
  'update_faculty_credentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'update_hotspot_ip' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'update_location_config' : IDL.Func(
      [LocationConfig],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'update_semester_template' : IDL.Func(
      [IDL.Nat, IDL.Vec(WeeklySlot)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'update_student' : IDL.Func(
      [IDL.Text, UpdateStudentRequest],
      [IDL.Variant({ 'ok' : Student, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ManualAttendanceRequest = IDL.Record({
    'prn' : IDL.Text,
    'subject' : IDL.Text,
    'timestamp_override' : IDL.Opt(IDL.Int),
    'notes' : IDL.Text,
  });
  const MarkAttendanceResponse = IDL.Variant({
    'ok' : IDL.Text,
    'alreadyMarked' : IDL.Text,
    'error' : IDL.Text,
    'invalidPRN' : IDL.Text,
  });
  const AddStudentRequest = IDL.Record({
    'prn' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'isActive' : IDL.Bool,
    'rollNo' : IDL.Nat,
  });
  const Student = IDL.Record({
    'id' : IDL.Text,
    'prn' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'isActive' : IDL.Bool,
    'rollNo' : IDL.Nat,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Text,
    'prn' : IDL.Text,
    'student_name' : IDL.Text,
    'latitude' : IDL.Float64,
    'method' : IDL.Text,
    'image_url' : IDL.Text,
    'device_info' : IDL.Text,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
    'geo_fail' : IDL.Bool,
  });
  const WeeklySlot = IDL.Record({
    'day' : IDL.Text,
    'startTime' : IDL.Text,
    'subject' : IDL.Text,
    'endTime' : IDL.Text,
    'room' : IDL.Text,
  });
  const AttendanceStats = IDL.Record({
    'unique_students' : IDL.Nat,
    'total_students' : IDL.Nat,
    'today_count' : IDL.Nat,
    'total_records' : IDL.Nat,
  });
  const FacultyCredentials = IDL.Record({
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const LocationConfig = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'locationLabel' : IDL.Text,
    'radiusMeters' : IDL.Float64,
  });
  const StudentWithId = IDL.Record({
    'prn_last2' : IDL.Text,
    'name' : IDL.Text,
    'student_id' : IDL.Text,
  });
  const SectionCounts = IDL.Record({
    'first_year' : IDL.Nat,
    'btech' : IDL.Nat,
    'third_year' : IDL.Nat,
    'second_year' : IDL.Nat,
  });
  const StudentWithSection = IDL.Record({
    'id' : IDL.Text,
    'prn' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'isActive' : IDL.Bool,
    'rollNo' : IDL.Nat,
  });
  const MarkAttendanceRequest = IDL.Record({
    'prn' : IDL.Text,
    'latitude' : IDL.Float64,
    'token' : IDL.Nat,
    'image_url' : IDL.Text,
    'device_info' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  const UpdateStudentRequest = IDL.Record({
    'prn' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'section' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
    'rollNo' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'add_manual_attendance' : IDL.Func(
        [ManualAttendanceRequest],
        [MarkAttendanceResponse],
        [],
      ),
    'add_student' : IDL.Func(
        [AddStudentRequest],
        [IDL.Variant({ 'ok' : Student, 'err' : IDL.Text })],
        [],
      ),
    'delete_attendance' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'delete_student' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'get_all_attendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'get_all_semester_templates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Vec(WeeklySlot)))],
        ['query'],
      ),
    'get_all_students' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'get_attendance_by_date' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'get_attendance_by_student' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'get_attendance_stats' : IDL.Func([], [AttendanceStats], ['query']),
    'get_faculty_credentials' : IDL.Func([], [FacultyCredentials], ['query']),
    'get_hotspot_ip' : IDL.Func([], [IDL.Text], ['query']),
    'get_live_checkins' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'get_location_config' : IDL.Func([], [LocationConfig], ['query']),
    'get_semester_template' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(WeeklySlot)],
        ['query'],
      ),
    'get_student_by_prn' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'get_student_list' : IDL.Func([], [IDL.Vec(StudentWithId)], ['query']),
    'get_student_sections_count' : IDL.Func([], [SectionCounts], ['query']),
    'get_students_by_section' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentWithSection)],
        ['query'],
      ),
    'mark_attendance' : IDL.Func(
        [MarkAttendanceRequest],
        [MarkAttendanceResponse],
        [],
      ),
    'update_faculty_credentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'update_hotspot_ip' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'update_location_config' : IDL.Func(
        [LocationConfig],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'update_semester_template' : IDL.Func(
        [IDL.Nat, IDL.Vec(WeeklySlot)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'update_student' : IDL.Func(
        [IDL.Text, UpdateStudentRequest],
        [IDL.Variant({ 'ok' : Student, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };