/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AddStudentRequest {
    prn: string;
    name: string;
    section: string;
    isActive: boolean;
    rollNo: bigint;
}
export interface StudentWithId {
    prn_last2: string;
    name: string;
    student_id: string;
}
export interface WeeklySlot {
    day: string;
    startTime: string;
    subject: string;
    endTime: string;
    room: string;
}
export type MarkAttendanceResponse = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "alreadyMarked";
    alreadyMarked: string;
} | {
    __kind__: "error";
    error: string;
} | {
    __kind__: "invalidPRN";
    invalidPRN: string;
};
export interface AttendanceStats {
    unique_students: bigint;
    total_students: bigint;
    today_count: bigint;
    total_records: bigint;
}
export interface FacultyCredentials {
    password: string;
    name: string;
    email: string;
}
export interface StudentWithSection {
    id: string;
    prn: string;
    reference_photo_url?: string;
    name: string;
    section: string;
    isActive: boolean;
    rollNo: bigint;
}
export interface SectionCounts {
    first_year: bigint;
    btech: bigint;
    third_year: bigint;
    second_year: bigint;
}
export interface ManualAttendanceRequest {
    prn: string;
    subject: string;
    timestamp_override?: bigint;
    notes: string;
}
export interface UpdateStudentRequest {
    prn?: string;
    name?: string;
    section?: string;
    isActive?: boolean;
    rollNo?: bigint;
}
export interface AttendanceRecord {
    id: string;
    prn: string;
    student_name: string;
    latitude: number;
    method: string;
    face_mismatch: boolean;
    image_url: string;
    device_info: string;
    longitude: number;
    timestamp: bigint;
    geo_fail: boolean;
}
export interface LocationConfig {
    lat: number;
    lng: number;
    locationLabel: string;
    radiusMeters: number;
}
export interface MarkAttendanceRequest {
    prn: string;
    latitude: number;
    token: bigint;
    image_url: string;
    device_info: string;
    longitude: number;
}
export interface Student {
    id: string;
    prn: string;
    reference_photo_url?: string;
    name: string;
    section: string;
    isActive: boolean;
    rollNo: bigint;
}
export interface backendInterface {
    add_manual_attendance(req: ManualAttendanceRequest): Promise<MarkAttendanceResponse>;
    add_student(req: AddStudentRequest): Promise<{
        __kind__: "ok";
        ok: Student;
    } | {
        __kind__: "err";
        err: string;
    }>;
    delete_attendance(record_id: bigint): Promise<boolean>;
    delete_student(id: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    flag_face_mismatch(record_id: bigint, flagged: boolean): Promise<boolean>;
    get_all_attendance(): Promise<Array<AttendanceRecord>>;
    get_all_semester_templates(): Promise<Array<[bigint, Array<WeeklySlot>]>>;
    get_all_students(): Promise<Array<Student>>;
    get_attendance_by_date(date_text: string): Promise<Array<AttendanceRecord>>;
    get_attendance_by_student(prn: string): Promise<Array<AttendanceRecord>>;
    get_attendance_stats(): Promise<AttendanceStats>;
    get_faculty_credentials(): Promise<FacultyCredentials>;
    get_hotspot_ip(): Promise<string>;
    get_live_checkins(limit: bigint): Promise<Array<AttendanceRecord>>;
    get_location_config(): Promise<LocationConfig>;
    get_semester_template(semester: bigint): Promise<Array<WeeklySlot>>;
    get_student_by_prn(prn: string): Promise<Student | null>;
    get_student_list(): Promise<Array<StudentWithId>>;
    get_student_sections_count(): Promise<SectionCounts>;
    get_students_by_section(section: string): Promise<Array<StudentWithSection>>;
    mark_attendance(req: MarkAttendanceRequest): Promise<MarkAttendanceResponse>;
    update_faculty_credentials(name: string, email: string, password: string): Promise<boolean>;
    update_hotspot_ip(ip: string): Promise<boolean>;
    update_location_config(config: LocationConfig): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    update_semester_template(semester: bigint, slots: Array<WeeklySlot>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    update_student(id: string, upd: UpdateStudentRequest): Promise<{
        __kind__: "ok";
        ok: Student;
    } | {
        __kind__: "err";
        err: string;
    }>;
    update_student_photo(prn: string, url: string): Promise<Student | null>;
}
import type { ManualAttendanceRequest as _ManualAttendanceRequest, MarkAttendanceResponse as _MarkAttendanceResponse, Student as _Student, StudentWithSection as _StudentWithSection, UpdateStudentRequest as _UpdateStudentRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async add_manual_attendance(arg0: ManualAttendanceRequest): Promise<MarkAttendanceResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.add_manual_attendance(to_candid_ManualAttendanceRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MarkAttendanceResponse_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.add_manual_attendance(to_candid_ManualAttendanceRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MarkAttendanceResponse_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async add_student(arg0: AddStudentRequest): Promise<{
        __kind__: "ok";
        ok: Student;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.add_student(arg0);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.add_student(arg0);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async delete_attendance(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.delete_attendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.delete_attendance(arg0);
            return result;
        }
    }
    async delete_student(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.delete_student(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.delete_student(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async flag_face_mismatch(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.flag_face_mismatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flag_face_mismatch(arg0, arg1);
            return result;
        }
    }
    async get_all_attendance(): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_all_attendance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_all_attendance();
            return result;
        }
    }
    async get_all_semester_templates(): Promise<Array<[bigint, Array<WeeklySlot>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_all_semester_templates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_all_semester_templates();
            return result;
        }
    }
    async get_all_students(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_all_students();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_all_students();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_attendance_by_date(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_attendance_by_date(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_attendance_by_date(arg0);
            return result;
        }
    }
    async get_attendance_by_student(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_attendance_by_student(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_attendance_by_student(arg0);
            return result;
        }
    }
    async get_attendance_stats(): Promise<AttendanceStats> {
        if (this.processError) {
            try {
                const result = await this.actor.get_attendance_stats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_attendance_stats();
            return result;
        }
    }
    async get_faculty_credentials(): Promise<FacultyCredentials> {
        if (this.processError) {
            try {
                const result = await this.actor.get_faculty_credentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_faculty_credentials();
            return result;
        }
    }
    async get_hotspot_ip(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.get_hotspot_ip();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_hotspot_ip();
            return result;
        }
    }
    async get_live_checkins(arg0: bigint): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_live_checkins(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_live_checkins(arg0);
            return result;
        }
    }
    async get_location_config(): Promise<LocationConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.get_location_config();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_location_config();
            return result;
        }
    }
    async get_semester_template(arg0: bigint): Promise<Array<WeeklySlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_semester_template(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_semester_template(arg0);
            return result;
        }
    }
    async get_student_by_prn(arg0: string): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.get_student_by_prn(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_student_by_prn(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_student_list(): Promise<Array<StudentWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_student_list();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_student_list();
            return result;
        }
    }
    async get_student_sections_count(): Promise<SectionCounts> {
        if (this.processError) {
            try {
                const result = await this.actor.get_student_sections_count();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_student_sections_count();
            return result;
        }
    }
    async get_students_by_section(arg0: string): Promise<Array<StudentWithSection>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_students_by_section(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_students_by_section(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async mark_attendance(arg0: MarkAttendanceRequest): Promise<MarkAttendanceResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.mark_attendance(arg0);
                return from_candid_MarkAttendanceResponse_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mark_attendance(arg0);
            return from_candid_MarkAttendanceResponse_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async update_faculty_credentials(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.update_faculty_credentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_faculty_credentials(arg0, arg1, arg2);
            return result;
        }
    }
    async update_hotspot_ip(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.update_hotspot_ip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_hotspot_ip(arg0);
            return result;
        }
    }
    async update_location_config(arg0: LocationConfig): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.update_location_config(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_location_config(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async update_semester_template(arg0: bigint, arg1: Array<WeeklySlot>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.update_semester_template(arg0, arg1);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_semester_template(arg0, arg1);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async update_student(arg0: string, arg1: UpdateStudentRequest): Promise<{
        __kind__: "ok";
        ok: Student;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.update_student(arg0, to_candid_UpdateStudentRequest_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_student(arg0, to_candid_UpdateStudentRequest_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async update_student_photo(arg0: string, arg1: string): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.update_student_photo(arg0, arg1);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_student_photo(arg0, arg1);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_MarkAttendanceResponse_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarkAttendanceResponse): MarkAttendanceResponse {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_StudentWithSection_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentWithSection): StudentWithSection {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    prn: string;
    reference_photo_url: [] | [string];
    name: string;
    section: string;
    isActive: boolean;
    rollNo: bigint;
}): {
    id: string;
    prn: string;
    reference_photo_url?: string;
    name: string;
    section: string;
    isActive: boolean;
    rollNo: bigint;
} {
    return {
        id: value.id,
        prn: value.prn,
        reference_photo_url: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.reference_photo_url)),
        name: value.name,
        section: value.section,
        isActive: value.isActive,
        rollNo: value.rollNo
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    alreadyMarked: string;
} | {
    error: string;
} | {
    invalidPRN: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "alreadyMarked";
    alreadyMarked: string;
} | {
    __kind__: "error";
    error: string;
} | {
    __kind__: "invalidPRN";
    invalidPRN: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "alreadyMarked" in value ? {
        __kind__: "alreadyMarked",
        alreadyMarked: value.alreadyMarked
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "invalidPRN" in value ? {
        __kind__: "invalidPRN",
        invalidPRN: value.invalidPRN
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Student;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Student;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Student_n6(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentWithSection>): Array<StudentWithSection> {
    return value.map((x)=>from_candid_StudentWithSection_n13(_uploadFile, _downloadFile, x));
}
function to_candid_ManualAttendanceRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ManualAttendanceRequest): _ManualAttendanceRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateStudentRequest_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateStudentRequest): _UpdateStudentRequest {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prn?: string;
    name?: string;
    section?: string;
    isActive?: boolean;
    rollNo?: bigint;
}): {
    prn: [] | [string];
    name: [] | [string];
    section: [] | [string];
    isActive: [] | [boolean];
    rollNo: [] | [bigint];
} {
    return {
        prn: value.prn ? candid_some(value.prn) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        section: value.section ? candid_some(value.section) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        rollNo: value.rollNo ? candid_some(value.rollNo) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prn: string;
    subject: string;
    timestamp_override?: bigint;
    notes: string;
}): {
    prn: string;
    subject: string;
    timestamp_override: [] | [bigint];
    notes: string;
} {
    return {
        prn: value.prn,
        subject: value.subject,
        timestamp_override: value.timestamp_override ? candid_some(value.timestamp_override) : candid_none(),
        notes: value.notes
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
